CREATE TABLE vendedores(
    V_ID INT NOT NULL AUTO_INCREMENT,
    V_NOMBRE VARCHAR(45),
    V_APELLIDO VARCHAR(45),
    V_TELEFONO VARCHAR(10),

    PRIMARY KEY (V_ID)
);

CREATE TABLE propiedades (
    P_ID INT AUTO_INCREMENT NOT NULL,
    V_ID INT NOT NULL,
    P_TITULO VARCHAR(45),
    P_PRECIO DECIMAL(10,2),
    P_IMAGEN VARCHAR(200),
    P_DESCRIPCION LONGTEXT,
    P_HABITACIONES INT(1),
    P_BANIO INT(1),
    P_DATECREATE DATE,
    
    PRIMARY KEY (P_ID),
    FOREIGN KEY (V_ID) REFERENCES vendedores(V_ID)
);

